sonar.projectKey=taskmaster-abdullah_todo-app-java
sonar.organization=taskmaster-abdullah
sonar.branches.autoConfigure=false
sonar.branch.name=main_postgres
sonar.branch.longLivedBranches.regex=(main|main_postgres|main_dev|develop|release/.*)

