### Base config
@host = http://localhost:8080

### 1) CREATE user
# @name createUser
POST {{host}}/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "abdullah"
}

> {%
    const body = response.body;
    if (body && body.id) {
        client.global.set("userId", body.id);
    }
%}

###

### 2) CREATE todolist (userId verplicht)
# @name createTodoList
POST {{host}}/api/todolists
Content-Type: application/json
Accept: application/json

{
  "userId": "{{userId}}",
  "title": "Werk",
  "description": "Taken voor deze week"
}

> {%
    const body = response.body;
    if (body && body.id) {
        client.global.set("todoListId", body.id);
    }
%}

###

### 3) ADD todo in lijst (maakt todo direct aan)
POST {{host}}/api/todolists/{{todoListId}}/todos
Content-Type: application/json
Accept: application/json

{
  "title": "API testen",
  "description": "Swagger endpoint testen",
  "priority": "HIGH"
}

###

### 4) READ todolist met todos
GET {{host}}/api/todolists/{{todoListId}}
Accept: application/json

> {%
    const body = response.body;
    if (body && body.todos && body.todos.length > 0) {
        client.global.set("todoId", body.todos[0].id);
    }
%}

###

### 5) REMOVE todo uit lijst (todo entity wordt ook verwijderd)
DELETE {{host}}/api/todolists/{{todoListId}}/todos/{{todoId}}

###

### 6) Controle: todo niet meer opvraagbaar
GET {{host}}/api/todos/{{todoId}}
Accept: application/json
