spring.application.name=demo.todo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatic table creation/updating
spring.jpa.hibernate.ddl-auto=update
# Display the SQL in logs
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# OpenAPI/Swagger endpoints
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# JWT config
app.jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.jwt.expiration-ms=3600000

