spring.application.name=demo.todo
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatic table creation/updating
spring.jpa.hibernate.ddl-auto=update
# Display the SQL in logs
spring.jpa.show-sql=true


# OpenAPI/Swagger endpoints
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# JWT config
app.jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.jwt.expiration-ms=3600000

